config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	# Defines the root path route ("/")
	root "users#index"

	devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

	#Resources routes
	resources :users, only: [:index] do
		resources :recipes, except: [:edit, :update] do
			resources :recipe_foods, only: [:new, :create, :destroy]
		end
		resources :foods, except: [:edit, :update]
	end
  resources :shopping_list, only: [:index]
	resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, foreign_key: 'food_id', class_name: 'RecipeFood', dependent: :delete_all

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id', class_name: 'RecipeFood', dependent: :delete_all
  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates_inclusion_of :public, in: [true, false]

  def amount_of_food
    recipe_foods.length
  end

  def total
    total_price = 0
    recipe_foods.each do |item|
      total_price += item.quantity * item.food.price
    end
    total_price
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :food_id, uniqueness: { scope: :recipe_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, foreign_key: 'user_id', class_name: 'Recipe'
  has_many :foods, foreign_key: 'user_id', class_name: 'Food'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = User.includes(:foods).find(params[:user_id])
  end

  def show; end

  def new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    food = Food.new(food_params)
    food.user_id = params[:user_id]
    respond_to do |format|
      format.html do
        if food.save
          redirect_to "/users/#{food.user_id}/foods"
          flash[:success] = 'Food added correctly'
        else
          redirect_to "/users/#{food.user_id}/foods/new"
          flash[:error] = 'ERROR! food wasn\'t added'
        end
      end
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy!
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:foods).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipe = Recipe.where(public: true).order(created_at: :desc).includes(:user, :recipe_foods,
                                                                           recipe_foods: [:food])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user_id: current_user)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.food_id = params[:food_id]
    recipe_food.recipe_id = params[:recipe_id]

    redirect_to user_recipe_path(id: params[:recipe_id])
    if recipe_food.save
      flash[:success] = 'Ingredient was added!'
    else
      flash[:error] = 'ERROR, Ingredient already exist!'
    end
  end

  def destroy
    RecipeFood.find(params[:id]).destroy
    redirect_to user_recipe_path(Recipe.find(params[:recipe_id]))
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.includes(:recipes).find(params[:user_id])
  end

  def show
    @user = User.includes(:recipes).find(params[:user_id])
    @recipe = @user.recipes.includes(:recipe_foods).find(params[:id])
    @current_user = current_user
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.user_id = params[:user_id]
    respond_to do |format|
      if @recipe.save!
        format.html do
          redirect_to user_recipe_path(@recipe.user_id, @recipe.id), notice: 'Recipe created successfully!'
        end
      else
        format.html { redirect_to new_user_recipes_path, alert: 'Failed to create recipe' }
      end
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy!
    redirect_to user_recipes_path, notice: 'Recipe deleted successfully!'
  end

  private

  def recipe_params
    params.require(:recipes).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @total_value = 0
    @total_items = 0
    @recipe_foods.each do |f|
      @total_value += f.quantity * f.food.price
      @total_items += 1
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def owner?(object)
    current_user == object.user
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rails Recipe App</title>
</head>
<body>
  <div class="index flex-col">
		<%= link_to "Add food", {controller: 'foods', action: 'new'}, class: 'btn-add' if @user.id == current_user.id%>
		<table class="table-container">
			<tr>
				<th>Food</th>
				<th>Measurement Unit</th>
				<th>Unit price</th>
				<th>Action</th>
			</tr>
			
			<%@user.foods.each do |food|%>
			<tr>
				<td><%=food.name%></td>
				<td><%=food.measurement_unit%></td>
				<td><%=food.price%>$</td>
				<td>
				<%= button_to "Delete", user_food_path(food.user_id, food.id), method: :delete if @user.id == current_user.id%>
				</td>
			</tr>
			<%end%>
		</table>
	<% flash.each do |name, msg| -%>
  	<%= content_tag :div, msg, class: "#{name} generic-alert" %>
  <% end -%>
  </div>
</body>
</html>

app/views/foods/new.html.erb
<%=render partial: "shared/food_form", locals: {user: current_user}%>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
		<% if user_signed_in? %>
		<nav class="navbar flex-row">
			<ul class="nav flex-row">
			<li><%= link_to 'Recipe App', root_path %></li>
			<li><%= link_to 'My food', user_foods_path(current_user.id)%></li>
			<li><%= link_to 'My recipe', user_recipes_path(current_user.id)%></li>
			<li><%= link_to 'Public recipe', public_recipes_path%></li>
			<li><%= link_to 'Log out', destroy_user_session_path, method: :delete%></li>
			</ul>
		</nav>
		<%end%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="index flex-col">
<h1>Public recipes</h1>
<% @recipe.each do |recipe|%>
	<div class="recipe flex-row">
		<div class="recipe-header flex-col">
			<p><%= link_to recipe.name, user_recipe_path(recipe.user.id, recipe.id), class: 'public-link'%></p>
			<strong><p>By: <%= recipe.user.name%></p></strong>
		</div>
		<div class="recipe-amount flex-col">
			<p>Total food items: <%= recipe.amount_of_food %></p>
			<p>Total price: <%= recipe.total%>$</p>
		</div>
	</div>
<%end%>
</div>

app/views/recipe_foods/new.html.erb
<div class="index flex-col">
  <h2>Add Ingredient!</h2>
  <div>
    <table>
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Quantity</th>
        <th>Action</th>
      </tr>
  <% @foods.each do |food| %>
    <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path do |f| %>
      <tr>
        <%= hidden_field_tag 'food_id', food.id %>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= f.number_field :quantity %></td>
        <td><%= f.submit 'Add ingredient' %></td>
      </tr>
    <% end %>
  <% end %>
</table>

</div>

</div>

app/views/recipes/_recipe.html.erb
<div class='recipe-b'>
  <div>
    <h2><%= link_to (recipe.name), user_recipe_path(recipe.user_id, recipe.id), class: "recipe-item"%></h2>
    
    <% if owner?(recipe) %>
      <div><%= button_to "Remove", user_recipe_path(recipe.user_id, recipe.id),
      method: :delete %></div>
  	<% end %>
    </div>

  <p><%=recipe.description%></p>
</div>

app/views/recipes/index.html.erb
<div class='index flex-col'>
	<div class="recipe-container">
	<div class='header-recipe'>
  	<h1>All recipes</h1>  
  	<% if @user==current_user %>
    	<button><%= link_to "Add new Recipe", new_user_recipe_path, class: "add-recipe"%></button>
  	<% end %>
	</div>

	<div class='content-recipe'>
  	<% @user.recipes.each do |recipe| %>
    	<%= render recipe %>
  	<%end%>
	</div>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="index flex-col">
<h1>New Recipe</h1>
<div class="new-cont">

<%= form_with(scope: :recipes, url: user_recipes_path(@user), method: :post, local: true) do |f| %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div>

  <div>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :preparation_time %><br />
    <%= f.number_field :preparation_time %>
  </div>

  <div>
    <%= f.label :cooking_time %><br />
    <%= f.number_field :cooking_time %>
  </div>

  <div>
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </div>

  <div>
    <%= f.submit "Add Recipe" %>
  </div>
<% end %>
</div>
</div>

app/views/recipes/show.html.erb
<div class="index flex-col">
	<h1 class='title'><%= @recipe.name %></h1>
	<div class='show-recipe'>
  	<section class='section-a'>
			<ul>
				<li>Preparation time: <%= @recipe.preparation_time %> hours</li>
				<li>Cooking time: <%= @recipe.cooking_time %> hours</li>
				<li><%= @recipe.description %></li>
			</ul>
			<button class="shop-list"><%= link_to 'Genrate shopping list', shopping_list_index_path(recipe_id: @recipe.id), class: "shop-link" %></button>
  	</section>
		<section class='section-b'>
			<ul>
				<% if @recipe.public == true %>
			  	<li class="public">Public</li>
				<% else %>
			  	<li class="private">Private</li>
				<% end %>
			<% if @recipe.user == @current_user%>
			</ul>
		<button class="shop-list">
		<%= link_to 'Add Ingredient!', new_user_recipe_recipe_food_path(user_id: @recipe.user_id, recipe_id: @recipe.id) %>
		</button>
		<% end %>
		</section>
	</div>
	<table class="table-container">
		<tr>
			<th>Food</th>
			<th>Quantity</th>
			<th>Value</th>
			<th>Actions</th>
		</tr>
		<% @recipe.recipe_foods.each do |recipe_food| %>
		<tr>
			<td><%= recipe_food.food.name %></td>
			<td><p><%= recipe_food.quantity %> <%=recipe_food.food.measurement_unit%></p></td>
			<td><%= recipe_food.food.price %></td>
			<td><% if recipe_food.recipe.user == @current_user%>
						<%= button_to 'Delete', user_recipe_recipe_food_path(id: recipe_food.id, recipe_id: recipe_food.recipe_id), method: :delete %>
  				<% end %>
  		</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/shared/_food_form.html.erb
<div class="index flex-col">
<h2>ADD NEW FOOD</h2>
<%= form_with scope: :foods, url: user_foods_path(user), 
	method: :post, local: true, class: "food-form" do |form|%>
  <div class="text-field flex-row">
		<%=form.label :name, "Food name: "%>
		<%= form.text_field :name%>
	</div>
	<div class="text-field flex-row">
		<%= form.label :price, "Price: "%>
		<%= form.number_field :price%>
	</div>
	<div class="text-field flex-row">
		<%= form.label :measurement_unit, "Measurement Unit: "%>
		<%= form.select :measurement_unit, ["grams", "units", "pounds", "kilogram", "milliliters","liters"]%>
	</div>
	<%= form.submit 'submit', class: "submit"%>
<% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "#{name} generic-alert" %>
<% end -%>
</div>

app/views/shopping_list/index.html.erb
<div class="index flex-col">
	<h2 class='title'>Shopping List</h2>
	<div class="flex-row shop-content">
  	<p>Amount of food items to buy: <%= @total_items %> Unit</p>
  	<p>Total value of food nested: <%= @total_value %>$</p>
	</div>
	
	<table class="table-container">
		<tr>
			<th>Food</th>
    	<th>Quantity</th>
    	<th>Price</th>
  	</tr>
  	<%@recipe_foods.each do |item|%>
  	<tr>
    	<td><%=item.food.name%></td>
    	<td><%=item.quantity%> <%= item.food.measurement_unit%></td>
    	<td><%=item.food.price * item.quantity%>$</td>
  	</tr>
  	<%end%>
	</table>
</div>

app/views/users/_user.html.erb
<h3><%= link_to ("List all recipes of #{user.name}"), user_recipes_path(user.id), class: "user-name" %></h3>

app/views/users/index.html.erb
<div class="user-container">
	<div class="users">
		<h2>Users</h2>
  		<% @users.each do |user| %>
				<div class='user'>
    			<%= render user %>
				</div>
  		<%end%>
	</div>
</div>